services: 
    netflix_update_household:
      logging:
        driver: "json-file"
        options:
          max-size: "200k"
          max-file: "10"
      container_name: netflix_update_household
      image: takalele/n_u_h:latest
      restart: unless-stopped
      mem_limit: 2048mb
      cpu_period: 100000
      cpu_quota: 25000
      environment:
        - 'NETFLIX_USERNAME=XXXXXX'
        - 'NETFLIX_PASSWORD=XXXXXX'
        - 'IMAP_USERNAME=XXXXXX'
        - 'IMAP_PASSWORD=XXXXXX'
        - 'IMAP_SERVER=imap.gmail.com'
        - 'IMAP_PORT=993'
        - 'MAILBOX=INBOX'
        - 'MAILBOX_TO=Netflix'
        - 'MOVE_TO_MAILBOX_TO=True'
        - 'MAILBOX_POLLING_SECONDS=3'
        - 'HEADLESS=True'
        - 'APPRISE_SERVICE_URL=tgram://XXXXXX:XXXXXX-XXXXXX/XXXXXX'
        - 'TZ=Europe/Vienna'
